apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: todo-app-staging

# Base reference
resources:
- ../../base
- namespace.yaml

# Namespace for staging
namespace: staging

# Name prefix for staging resources
namePrefix: staging-

# Common annotations for staging
commonAnnotations:
  cost-center: development
  deployment.environment: staging

# Patches for staging-specific configurations
patches:
  # Set replica count to 1 for staging
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: user-service

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-service

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend

  # Remove namespace from resources (kustomize will apply staging namespace)
  - patch: |-
      - op: remove
        path: /metadata/namespace
    target:
      group: apps
      version: v1
      kind: Deployment

  - patch: |-
      - op: remove
        path: /metadata/namespace
    target:
      version: v1
      kind: Service

  - patch: |-
      - op: remove
        path: /metadata/namespace
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress

  # Update SECRET_KEY for staging environment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging-secret-key-change-in-production"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: user-service

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging-secret-key-change-in-production"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-service

  # Update ingress host for staging
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "todo-app.local"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: todo-app-ingress

# Image tag updates for staging
images:
- name: ghcr.io/keremar/todo-app-user-service
  newTag: latest
- name: ghcr.io/keremar/todo-app-todo-service
  newTag: latest
- name: ghcr.io/keremar/todo-app-frontend
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    environment: staging
    tier: non-production
