# jenkins-rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-agent-manager
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "secrets", "events"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-manager-binding
  namespace: jenkins # DİKKAT: Jenkins'in kurulu olduğu namespace
subjects:
- kind: ServiceAccount
  name: jenkins # Helm ile kurulan Service Account'un adı
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-agent-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-manager-binding-default-ns
  namespace: default # DİKKAT: Yetkinin verileceği namespace
subjects:
- kind: ServiceAccount
  name: jenkins # Yetkiyi alacak Service Account
  namespace: jenkins # Service Account'un bulunduğu namespace
roleRef:
  kind: ClusterRole
  name: jenkins-agent-manager
  apiGroup: rbac.authorization.k8s.io
