apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    name: todo-app

---

apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins

---

apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  labels:
    name: sonarqube
