apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: todo-app-base

# Base resources - local YAML files
resources:
- user-service-deployment.yaml
- user-service-service.yaml
- todo-service-deployment.yaml
- todo-service-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml

# Common annotations
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

# Images to be replaced during build
images:
- name: ghcr.io/keremar/todo-app-user-service
  newTag: latest
- name: ghcr.io/keremar/todo-app-todo-service
  newTag: latest
- name: ghcr.io/keremar/todo-app-frontend
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: microservices
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/version: 1.0.0
